---
.travis.yml:
  docker_sets:
    - set: ubuntu1604-64
    - set: ubuntu1804-64
    - set: centos6-64
    - set: centos7-64
    - set: debian8-64
    - set: debian9-64
    - set: debian10-64
  secure: "aK1I5ctuuB7eGuaOUT/pJRB3U/L1chtiA18a2WDmRXYX/5mvryqNFAm/64oxxOeXmALbjAmMacDW2jMMDJcU6ZVm5i/V7D4wfa/rcTZxUCwxspa4yhWba1c/NGzElz201NKWHscHhY657egC0iIUe8PERSrGQpFPi2RyuAcOfyH+46cP7iuJUPsa5jIF8E2eyMnaQOhuyjBH+XYsH5q1xzpfCJCpCoqagmyJXTcdrYpNGTEux7bc2N+bLEWnjK+Rlhvgnq+D1xK/uCtKv2yLd+ackgSPbtGJ52xWMpJKyutgzzgEMaNakK91TkZJuZg9esQXmiHbuj/gx5to+JKXWN/yfK4Jm91HetOcd0azPysszmcQnQdRa3S2fbafBsqvvyjnGFtCOdI7T9CN0kzcKJZlgsqOE8a+TwuSn+fHdFZB99XXpk/cd+hyn3NfZPXYJtmq3hEwxYVytd7wqPvNvvBULZW+nGrQ6TI2lQ7Hf5hy/kWoKT9MB1PiZRfwEaTfNM88nUTl+Wabnb2dGtsZuty1KiOEHRySLnX1SCjl7Mbb0uxQc2lmj9Z8vQFp7WEPspQemNs6Byz/pYIUytjSwo7Z+oRc56VMf/T27DqGDSGjC7wzPsOZGF8r0D/cQ8Iziyd9F9/dqs00DDV5l7C3Q8qpg4JIN8ZgTfucgQvkO8k="
Gemfile:
  optional:
    ':test':
      - gem: 'puppet-lint-legacy_fact-check'
      - gem: 'puppet-lint-param-docs'
      - gem: 'irb'
spec/spec_helper_acceptance.rb:
  unmanaged: false
